name: Validation Steps (action)

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: string
      infra_commons_tag:
        required: false
        type: string
        default: ''
      enable_kube_linter:
        description: 'Enable Kube-linter validation'
        required: false
        type: boolean
        default: false
      strict_kube_linter_checks:
        description: 'Enable strict kube-linter checks'
        required: false
        type: boolean
        default: false
      enable_argocd_validation:
        description: 'Enable ArgoCD validation'
        required: false
        type: boolean
        default: false
      enable_argocd_schema_validation:
        description: 'Enable ArgoCD schema validation'
        required: false
        type: boolean
        default: false
      repo_structure_validation_warning_only:
        description: 'Enable warning only mode for repo structure validation'
        required: false
        type: boolean
        default: false

jobs:
  validation:
    name: Validation Steps
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Run common deployment validation action
        uses: ./.github/actions/common-deployment-values-validation
        with:
          environment: ${{ inputs.environment }}
          infra_commons_tag: ${{ inputs.infra_commons_tag }}
          enable_kube_linter: ${{ inputs.enable_kube_linter }}
          strict_kube_linter_checks: ${{ inputs.strict_kube_linter_checks }}
          enable_argocd_validation: ${{ inputs.enable_argocd_validation }}
          enable_argocd_schema_validation: ${{ inputs.enable_argocd_schema_validation }}
          repo_structure_validation_warning_only: ${{ inputs.repo_structure_validation_warning_only }}

