name: Reusable Terraform Pre-Commit Checks

on:
  workflow_call:
    inputs:
      discovery_mode:
        required: false
        type: string
        default: ""
        # expected values: "modules", "env-roots", "auto", "" (default: "")
      search_path:
        required: false
        type: string
        default: .
      tfversion:
        required: false
        type: string
        default: "" # if empty, the workflow will attempt to compute the Terraform version for each root using the existing logic in compute-tf-version.sh
      precommit_image_version:
        required: false
        type: string
        default: "latest" # if not provided, the workflow will use the latest version of the pre-commit image from Docker Hub. This allows callers to specify a custom image version if needed (e.g. to test against a specific pre-commit version or to use a custom image with additional tools/plugins pre-installed).


env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  TF_LINT_VERSION: "v0.61.0"
  TFLINT_PLUGIN_DIR: ${{ github.workspace }}/.tflint.d/plugins
  PRECOMMIT_CONFIG: ${{ github.workspace }}/.pre-commit-config.yaml # precommit version local to caller repository
  INFRA_COMMONS_REPO: pagopa/interop-infra-commons
  # todo rivedere
  INFRA_COMMONS_REF: feature/pin-9552-tf-check-precommit # temporary branch for testing, should be updated to a stable reference (e.g. main or a release tag)
  INFRA_COMMONS_PATH: .terraform-precommit-workflows # destination path for the checked out infra-commons repository within the workflow
  INFRA_COMMONS_SCRIPTS_RELATIVE_PATH: scripts/terraform

permissions:
  contents: read

jobs:
  discover:
    name: Discover Terraform roots
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.discover.outputs.matrix }}

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Checkout infra-commons workflow repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: ${{ env.INFRA_COMMONS_REPO }}
          ref: ${{ env.INFRA_COMMONS_REF }}
          path: ${{ env.INFRA_COMMONS_PATH }}
          sparse-checkout: |
            ${{ env.INFRA_COMMONS_SCRIPTS_RELATIVE_PATH }}

      # TODO splittare il workflow -> discovery step solo per infra commons, rimuovere dal reusable workflow 
      - name: Discover Terraform roots
        id: discover
        env:
          INFRA_COMMONS_PATH: ${{ env.INFRA_COMMONS_PATH }}
          INFRA_COMMONS_SCRIPTS_RELATIVE_PATH: ${{ env.INFRA_COMMONS_SCRIPTS_RELATIVE_PATH }}
          DISCOVERY_MODE: ${{ inputs.discovery_mode }}
          SEARCH_PATH: ${{ inputs.search_path }}
        run: |
          set -euo pipefail

          if [ -z "$DISCOVERY_MODE" ]; then
            echo "No discovery mode specified, defaulting to single root: $SEARCH_PATH"
            matrix="$(jq -cn --arg path "$SEARCH_PATH" --arg name "$(basename "$SEARCH_PATH")" '{include:[{path: $path, name: $name}]}')"
            echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          discovery_script="$INFRA_COMMONS_PATH/$INFRA_COMMONS_SCRIPTS_RELATIVE_PATH/discover-terraform-roots.sh"
          echo "Discovering Terraform roots using script: $discovery_script"

          if [ ! -x "$discovery_script" ]; then
            echo "::error::Missing executable script: $discovery_script"
            exit 1
          fi

          matrix="$(
            "$discovery_script" \
              "$DISCOVERY_MODE" \
              "$SEARCH_PATH"
          )"

          matrix="$(echo "$matrix" | jq -c '.')"

          echo "$matrix"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  checks:
    name: "[${{ matrix.name }}] Terraform checks" # TODO check composite w/matrix
    needs: discover
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Checkout central workflow repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: ${{ env.INFRA_COMMONS_REPO }}
          ref: ${{ env.INFRA_COMMONS_REF }}
          path: ${{ env.INFRA_COMMONS_PATH }}
          sparse-checkout: |
            ${{ env.INFRA_COMMONS_SCRIPTS_RELATIVE_PATH }}
            .tflint.hcl

      - name: Compute Terraform version
        id: tf-version
        env:
          INFRA_COMMONS_PATH: ${{ env.INFRA_COMMONS_PATH }}
          INFRA_COMMONS_SCRIPTS_RELATIVE_PATH: ${{ env.INFRA_COMMONS_SCRIPTS_RELATIVE_PATH }}
          PROVIDED_TF_VERSION: ${{ inputs.tfversion }}
          ROOT: ${{ matrix.path }}
        run: |
          set -euo pipefail

          # If tfversion input is provided, use it directly without running the discovery script.
          # This allows the caller workflow to override the Terraform version discovery logic when needed 
          # (e.g. if the .terraform-version file is missing or if a specific version needs to be enforced for the checks).
          if [ -n "$PROVIDED_TF_VERSION" ]; then
            echo "Using provided Terraform version: $PROVIDED_TF_VERSION"
            echo "tf_version=$PROVIDED_TF_VERSION" >> "$GITHUB_OUTPUT"
            echo "tf_version_hash=$(echo "$PROVIDED_TF_VERSION" | sha256sum | awk '{print $1}')" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # If tfversion input is empty, run the discovery script to compute the Terraform version for the current root.
          script="$INFRA_COMMONS_PATH/$INFRA_COMMONS_SCRIPTS_RELATIVE_PATH/compute-tf-version.sh"
          root="$ROOT"

          if [ ! -x "$script" ]; then
            echo "::error::Missing executable script: $script"
            exit 1
          fi

          tf_version="$("$script" "$GITHUB_WORKSPACE/$root")"
          tf_version="$(echo "$tf_version" | xargs)"

          echo "Terraform version for $root: $tf_version"
          echo "tf_version=$tf_version" >> "$GITHUB_OUTPUT"
          echo "tf_version_hash=$(echo "$tf_version" | sha256sum | awk '{print $1}')" >> "$GITHUB_OUTPUT"

      - name: Ensure cache dirs
        run: |
          mkdir -p "${TF_PLUGIN_CACHE_DIR}"
          mkdir -p "${TFLINT_PLUGIN_DIR}"

      - name: Cache Terraform plugins
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: tf-${{ runner.os }}-${{ steps.tf-version.outputs.tf_version_hash }}

      - name: Setup Terraform ${{ steps.tf-version.outputs.tf_version }}
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.tf-version.outputs.tf_version }}

      - name: Show Terraform version
        run: terraform version

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@6770de8d186019a148cc2b144e8bfa627f7d4aa8
        with:
          tflint_version: ${{ env.TF_LINT_VERSION }}

      - name: Cache TFLint plugins
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ${{ env.TFLINT_PLUGIN_DIR }}
          key: tflint-${{ env.TF_LINT_VERSION }}-${{ hashFiles('**/.tflint.hcl') }}
          restore-keys: |
            tflint-${{ env.TF_LINT_VERSION }}-
            tflint-

      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: Run pre-commit on Terraform root
        env:
          ROOT: ${{ matrix.path }}
          INFRA_COMMONS_PATH: ${{ env.INFRA_COMMONS_PATH }}
          PRECOMMIT_IMAGE_VERSION: ${{ inputs.precommit_image_version }}
        run: |
          set -euo pipefail

          root="$ROOT"
          infra_commons_abs="$GITHUB_WORKSPACE/$INFRA_COMMONS_PATH"

          # unset TF_PLUGIN_CACHE_DIR

          if [ -z "$(find "$root" -type f \( -name '*.tf' -o -name '*.tfvars' \) -print -quit)" ]; then
            echo "No Terraform files found in $root, skipping."
            exit 0
          fi

          tflint_config="$infra_commons_abs/.tflint.hcl"
          if [ ! -f "$tflint_config" ]; then
            echo "::error::.tflint.hcl not found in checked out infra-commons path: $tflint_config"
            exit 1
          fi

          docker run \
            -v "$(pwd):/lint" \
            -w /lint \
            ghcr.io/antonbabenko/pre-commit-terraform:$PRECOMMIT_IMAGE_VERSION \
            run -a
            # --show-diff-on-failure
            # --config not necessary

  gate:
    name: Terraform CI Gate
    if: always()
    needs: checks
    runs-on: ubuntu-24.04

    steps:
      - name: Check matrix jobs status
        env:
          CHECKS_RESULT: ${{ needs.checks.result }}
        run: |
          result="$CHECKS_RESULT"
          if [[ "$result" != "success" ]]; then
            echo "::error title=Terraform CI Gate::One or more Terraform checks failed: $result"
            exit 1
          fi

          echo "Terraform CI Gate: all Terraform checks passed."
